# Generated by Django 5.1.7 on 2025-03-30 08:39

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # docker, Linux 환경에서 pgvector 확장 프로그램 설치는 되어있지만 활성화 필요
        VectorExtension(),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3, editable=False)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='item_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
