# Generated by Django 5.1.7 on 2025-04-13 03:48

import chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_paikdabangmenudocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paikdabangmenudocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='paikdabangmenudocument',
            name='page_content',
            field=models.TextField(validators=[chat.validators.MaxTokenValidator()]),
        ),
    ]
